import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1785740115392 implements MigrationInterface {
    name = ' $npmConfigName1785740115392'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`branch\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(150) NOT NULL, \`code\` varchar(20) NOT NULL, \`type\` enum ('STORE', 'WAREHOUSE') NOT NULL DEFAULT 'STORE', \`address\` text NULL, \`city\` varchar(100) NULL, \`phone\` varchar(20) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_638479fc29fab932b7ab0aea91\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(150) NOT NULL, \`email\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`role\` enum ('SUPER_ADMIN', 'ADMIN', 'CENTRAL_INVENTORY_MANAGER', 'FINANCE', 'BRANCH_MANAGER', 'BRANCH_INVENTORY', 'BRANCH_FRONT_OFFICE') NOT NULL, \`branch_id\` varchar(36) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`last_login_at\` datetime NULL, \`created_by_id\` varchar(36) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_reset_token\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, \`token_hash\` varchar(255) NOT NULL, \`expires_at\` datetime NOT NULL, \`used_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_7eabb22ed38459ffc24dc8b415\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`refresh_token\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, \`token_hash\` varchar(255) NOT NULL, \`expires_at\` datetime NOT NULL, \`revoked_at\` datetime NULL, \`user_agent\` varchar(512) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_6bbe63d2fe75e7f0ba1710351d\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`system_setting\` (\`key\` varchar(100) NOT NULL, \`value\` json NOT NULL, \`updated_by_id\` varchar(36) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`key\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`restock_request\` (\`id\` varchar(36) NOT NULL, \`branch_id\` varchar(36) NOT NULL, \`requested_by_id\` varchar(36) NOT NULL, \`status\` enum ('PENDING', 'APPROVED', 'PARTIALLY_APPROVED', 'REJECTED', 'FULFILLED', 'RECEIVED') NOT NULL DEFAULT 'PENDING', \`reviewed_by_id\` varchar(36) NULL, \`review_note\` text NULL, \`reviewed_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`author\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(200) NOT NULL, \`bio\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`publisher\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(200) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`category\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(150) NOT NULL, \`parent_id\` varchar(36) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`book\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(500) NOT NULL, \`isbn\` varchar(50) NOT NULL, \`barcode\` varchar(100) NOT NULL, \`description\` text NULL, \`price\` decimal(10,2) NOT NULL, \`cost_price\` decimal(10,2) NULL, \`cover_image_url\` varchar(500) NULL, \`author_id\` varchar(36) NOT NULL, \`publisher_id\` varchar(36) NOT NULL, \`category_id\` varchar(36) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_c10a44a29ef231062f22b1b7ac\` (\`title\`), UNIQUE INDEX \`IDX_bd183604b9c828c0bdd92cafab\` (\`isbn\`), UNIQUE INDEX \`IDX_cd08784c80b056b4b3ad1d8530\` (\`barcode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`restock_request_item\` (\`id\` varchar(36) NOT NULL, \`restock_request_id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NOT NULL, \`quantity_requested\` int NOT NULL, \`quantity_approved\` int NOT NULL DEFAULT '0', \`quantity_received\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(200) NOT NULL, \`contact_person\` varchar(150) NULL, \`phone\` varchar(20) NULL, \`email\` varchar(255) NULL, \`address\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_order\` (\`id\` varchar(36) NOT NULL, \`order_number\` varchar(50) NOT NULL, \`supplier_id\` varchar(36) NOT NULL, \`status\` enum ('DRAFT', 'PLACED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT', \`expected_date\` date NULL, \`placed_by_id\` varchar(36) NOT NULL, \`total_cost\` decimal(10,2) NOT NULL DEFAULT '0.00', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a932de191f1a55173e4b985c6e\` (\`order_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_order_item\` (\`id\` varchar(36) NOT NULL, \`purchase_order_id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NOT NULL, \`quantity_ordered\` int NOT NULL, \`quantity_received\` int NOT NULL DEFAULT '0', \`unit_cost\` decimal(10,2) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stock_movement\` (\`id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NOT NULL, \`branch_id\` varchar(36) NULL, \`type\` enum ('SALE', 'SALE_VOID', 'RESTOCK_IN', 'TRANSFER_OUT', 'TRANSFER_IN', 'EXHIBITION_OUT', 'EXHIBITION_RETURN', 'ADJUSTMENT') NOT NULL, \`reason\` enum ('DAMAGED', 'LOST', 'SAMPLE', 'RETURNED_TO_SUPPLIER', 'CORRECTION') NULL, \`quantity\` int NOT NULL, \`reference_type\` enum ('BILL', 'RESTOCK_REQUEST', 'EXHIBITION', 'PURCHASE_ORDER', 'MANUAL') NULL, \`reference_id\` varchar(36) NULL, \`performed_by_id\` varchar(36) NOT NULL, \`note\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_9693db35471541ee9be35cbc03\` (\`reference_type\`, \`reference_id\`), INDEX \`IDX_8f9d1d7f22359317d47323bc72\` (\`branch_id\`, \`created_at\`), INDEX \`IDX_b69efe8c6a15376cb182f44e57\` (\`book_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`central_stock\` (\`id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NOT NULL, \`quantity\` int NOT NULL DEFAULT '0', \`reorder_threshold\` int NOT NULL DEFAULT '20', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2ad058e8f4d1c74cc23d395872\` (\`book_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`branch_inventory\` (\`id\` varchar(36) NOT NULL, \`branch_id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NOT NULL, \`quantity\` int NOT NULL DEFAULT '0', \`reorder_threshold\` int NOT NULL DEFAULT '5', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4c379d2a60ddcd889211ecda17\` (\`branch_id\`, \`book_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expense\` (\`id\` varchar(36) NOT NULL, \`branch_id\` varchar(36) NULL, \`category\` enum ('RENT', 'SALARY', 'UTILITIES', 'SUPPLIES', 'MAINTENANCE', 'MARKETING', 'OTHER') NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`description\` text NOT NULL, \`expense_date\` date NOT NULL, \`entered_by_id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expense_revision\` (\`id\` varchar(36) NOT NULL, \`expense_id\` varchar(36) NOT NULL, \`previous_amount\` decimal(10,2) NOT NULL, \`previous_description\` text NOT NULL, \`changed_by_id\` varchar(36) NOT NULL, \`changed_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash_reconciliation\` (\`id\` varchar(36) NOT NULL, \`branch_id\` varchar(36) NOT NULL, \`reconciliation_date\` date NOT NULL, \`system_cash_total\` decimal(10,2) NOT NULL, \`counted_cash_total\` decimal(10,2) NOT NULL, \`variance\` decimal(10,2) NOT NULL, \`note\` text NULL, \`reconciled_by_id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_476f8f82c63cd5222862f07ff0\` (\`branch_id\`, \`reconciliation_date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exhibition\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(200) NOT NULL, \`location\` varchar(300) NOT NULL, \`source_branch_id\` varchar(36) NOT NULL, \`start_date\` date NOT NULL, \`end_date\` date NOT NULL, \`status\` enum ('REQUESTED', 'APPROVED', 'REJECTED', 'ONGOING', 'CLOSED') NOT NULL DEFAULT 'REQUESTED', \`requested_by_id\` varchar(36) NOT NULL, \`approved_by_id\` varchar(36) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exhibition_stock\` (\`id\` varchar(36) NOT NULL, \`exhibition_id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NOT NULL, \`quantity_taken\` int NOT NULL, \`quantity_sold\` int NOT NULL DEFAULT '0', \`quantity_returned\` int NOT NULL DEFAULT '0', \`quantity_damaged\` int NOT NULL DEFAULT '0', \`quantity_lost\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_444c894652459cf6f9f4fd01b4\` (\`exhibition_id\`, \`book_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`new_title_request\` (\`id\` varchar(36) NOT NULL, \`free_text_title\` text NOT NULL, \`author\` varchar(200) NULL, \`isbn\` varchar(50) NULL, \`requested_by_id\` varchar(36) NOT NULL, \`enquiry_count\` int NOT NULL DEFAULT '1', \`status\` enum ('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING', \`reviewed_by_id\` varchar(36) NULL, \`created_book_id\` varchar(36) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`book_enquiry\` (\`id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NULL, \`free_text_title\` text NULL, \`branch_id\` varchar(36) NOT NULL, \`logged_by_id\` varchar(36) NOT NULL, \`customer_name\` varchar(150) NULL, \`customer_phone\` varchar(20) NULL, \`status\` enum ('OPEN', 'STOCK_REQUESTED', 'NEW_TITLE_REQUESTED', 'FULFILLED', 'CLOSED') NOT NULL DEFAULT 'OPEN', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bill\` (\`id\` varchar(36) NOT NULL, \`bill_number\` varchar(50) NOT NULL, \`branch_id\` varchar(36) NOT NULL, \`exhibition_id\` varchar(36) NULL, \`created_by_id\` varchar(36) NOT NULL, \`sub_total\` decimal(10,2) NOT NULL, \`discount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total_amount\` decimal(10,2) NOT NULL, \`payment_status\` enum ('PAID', 'UNPAID') NOT NULL, \`payment_mode\` enum ('CASH', 'UPI') NULL, \`status\` enum ('COMPLETED', 'VOIDED') NOT NULL DEFAULT 'COMPLETED', \`voided_by_id\` varchar(36) NULL, \`void_reason\` text NULL, \`voided_at\` datetime NULL, \`customer_name\` varchar(150) NULL, \`customer_phone\` varchar(20) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_10443f7ef374882cc97406cb32\` (\`branch_id\`, \`created_at\`), INDEX \`IDX_3948e00da8f516a2315cd9e102\` (\`created_at\`), UNIQUE INDEX \`IDX_e897f48daabe3b9132f9343232\` (\`bill_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bill_item\` (\`id\` varchar(36) NOT NULL, \`bill_id\` varchar(36) NOT NULL, \`book_id\` varchar(36) NOT NULL, \`quantity\` int NOT NULL, \`unit_price\` decimal(10,2) NOT NULL, \`line_total\` decimal(10,2) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`audit_log\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, \`action\` varchar(100) NOT NULL, \`entity_type\` varchar(100) NOT NULL, \`entity_id\` varchar(36) NULL, \`before_json\` json NULL, \`after_json\` json NULL, \`ip_address\` varchar(45) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_2ad7930a7c2af80585c8c1b770\` (\`created_at\`), INDEX \`IDX_43fef0ec7f613c19c612fffe62\` (\`entity_type\`, \`entity_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_09210cab0384d041d5f3b337e8e\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_b489bba7c2e3d5afcd98a445ff8\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset_token\` ADD CONSTRAINT \`FK_7eabb22ed38459ffc24dc8b415d\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refresh_token\` ADD CONSTRAINT \`FK_6bbe63d2fe75e7f0ba1710351d4\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`system_setting\` ADD CONSTRAINT \`FK_811f9e6d65126e0164f87b29a55\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restock_request\` ADD CONSTRAINT \`FK_2f71a73309b78681fe8f9af1309\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restock_request\` ADD CONSTRAINT \`FK_6a60b5f26ee8d962e1cda114e59\` FOREIGN KEY (\`requested_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restock_request\` ADD CONSTRAINT \`FK_46de05bb7eb9d1d581b6cd8157b\` FOREIGN KEY (\`reviewed_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`FK_1117b4fcb3cd4abb4383e1c2743\` FOREIGN KEY (\`parent_id\`) REFERENCES \`category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book\` ADD CONSTRAINT \`FK_24b753b0490a992a6941451f405\` FOREIGN KEY (\`author_id\`) REFERENCES \`author\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book\` ADD CONSTRAINT \`FK_baaa4c0d27070b4125aa5a81e25\` FOREIGN KEY (\`publisher_id\`) REFERENCES \`publisher\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book\` ADD CONSTRAINT \`FK_0bfe418ce140d4720d0eede7c3e\` FOREIGN KEY (\`category_id\`) REFERENCES \`category\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restock_request_item\` ADD CONSTRAINT \`FK_f57c579468c74127aa1500781d8\` FOREIGN KEY (\`restock_request_id\`) REFERENCES \`restock_request\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restock_request_item\` ADD CONSTRAINT \`FK_7d2f087c1802f52757cd0d2a52f\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_order\` ADD CONSTRAINT \`FK_3dacab5c4a43cecc0e48f5edb12\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`supplier\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_order\` ADD CONSTRAINT \`FK_d430e0c1b1e96453b7403795268\` FOREIGN KEY (\`placed_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_order_item\` ADD CONSTRAINT \`FK_1c77f592d2af177be137dac042a\` FOREIGN KEY (\`purchase_order_id\`) REFERENCES \`purchase_order\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_order_item\` ADD CONSTRAINT \`FK_32398344c68461ebb37c86935bc\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock_movement\` ADD CONSTRAINT \`FK_41586e8268043b2847ec4c9f718\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock_movement\` ADD CONSTRAINT \`FK_3695701a949574c5d636d13e218\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock_movement\` ADD CONSTRAINT \`FK_7484d49153e7188cc2f147f1f90\` FOREIGN KEY (\`performed_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`central_stock\` ADD CONSTRAINT \`FK_2ad058e8f4d1c74cc23d395872f\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branch_inventory\` ADD CONSTRAINT \`FK_6cd826d26d62acf07e7ae226f75\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branch_inventory\` ADD CONSTRAINT \`FK_17b568948c94b4ac9314fee3bdd\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_6ae83e254854a25f788cf9f3495\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_c9b6a471b795457f5307c477e50\` FOREIGN KEY (\`entered_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense_revision\` ADD CONSTRAINT \`FK_6098607116ed775b4791cc99b09\` FOREIGN KEY (\`expense_id\`) REFERENCES \`expense\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense_revision\` ADD CONSTRAINT \`FK_586a7ef066aa9c3dd2aa65c6901\` FOREIGN KEY (\`changed_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash_reconciliation\` ADD CONSTRAINT \`FK_09cd6f2e176e72e3e96c03f41c5\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash_reconciliation\` ADD CONSTRAINT \`FK_26d6dd44f75ec0a907829b03c12\` FOREIGN KEY (\`reconciled_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exhibition\` ADD CONSTRAINT \`FK_0d5dcefa3cff367e6d0ade75cd8\` FOREIGN KEY (\`source_branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exhibition\` ADD CONSTRAINT \`FK_083d1d8f037bc8591e2f8c14d76\` FOREIGN KEY (\`requested_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exhibition\` ADD CONSTRAINT \`FK_502413e750aee25c438c972e2de\` FOREIGN KEY (\`approved_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exhibition_stock\` ADD CONSTRAINT \`FK_88f7647cc25073a57dbc090b9a6\` FOREIGN KEY (\`exhibition_id\`) REFERENCES \`exhibition\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exhibition_stock\` ADD CONSTRAINT \`FK_4707c538e0dfbb2916f2c6e57f7\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`new_title_request\` ADD CONSTRAINT \`FK_e8b0487f6e2adba3f7dd38daa16\` FOREIGN KEY (\`requested_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`new_title_request\` ADD CONSTRAINT \`FK_c43ae9667d3d70ce8dcef25c814\` FOREIGN KEY (\`reviewed_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`new_title_request\` ADD CONSTRAINT \`FK_33b528b4fe87f4167cf39fd123f\` FOREIGN KEY (\`created_book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_enquiry\` ADD CONSTRAINT \`FK_1bb1cc08ba28baec9fb3fca027e\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_enquiry\` ADD CONSTRAINT \`FK_0ed3726b7125cf22d1c76e4b318\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_enquiry\` ADD CONSTRAINT \`FK_54d4f257f16dba244b75ab99317\` FOREIGN KEY (\`logged_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill\` ADD CONSTRAINT \`FK_d9ccc98214fa9cbcc4cb99be42e\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branch\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill\` ADD CONSTRAINT \`FK_e9f71888234c854dfeac2742e14\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill\` ADD CONSTRAINT \`FK_3218e1fea681b8ecbf4944edb07\` FOREIGN KEY (\`voided_by_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_item\` ADD CONSTRAINT \`FK_fe0fba0a43c5182491a8e6cb103\` FOREIGN KEY (\`bill_id\`) REFERENCES \`bill\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_item\` ADD CONSTRAINT \`FK_d981fefe014b876f8701f17762c\` FOREIGN KEY (\`book_id\`) REFERENCES \`book\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`audit_log\` ADD CONSTRAINT \`FK_cb11bd5b662431ea0ac455a27d7\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`audit_log\` DROP FOREIGN KEY \`FK_cb11bd5b662431ea0ac455a27d7\``);
        await queryRunner.query(`ALTER TABLE \`bill_item\` DROP FOREIGN KEY \`FK_d981fefe014b876f8701f17762c\``);
        await queryRunner.query(`ALTER TABLE \`bill_item\` DROP FOREIGN KEY \`FK_fe0fba0a43c5182491a8e6cb103\``);
        await queryRunner.query(`ALTER TABLE \`bill\` DROP FOREIGN KEY \`FK_3218e1fea681b8ecbf4944edb07\``);
        await queryRunner.query(`ALTER TABLE \`bill\` DROP FOREIGN KEY \`FK_e9f71888234c854dfeac2742e14\``);
        await queryRunner.query(`ALTER TABLE \`bill\` DROP FOREIGN KEY \`FK_d9ccc98214fa9cbcc4cb99be42e\``);
        await queryRunner.query(`ALTER TABLE \`book_enquiry\` DROP FOREIGN KEY \`FK_54d4f257f16dba244b75ab99317\``);
        await queryRunner.query(`ALTER TABLE \`book_enquiry\` DROP FOREIGN KEY \`FK_0ed3726b7125cf22d1c76e4b318\``);
        await queryRunner.query(`ALTER TABLE \`book_enquiry\` DROP FOREIGN KEY \`FK_1bb1cc08ba28baec9fb3fca027e\``);
        await queryRunner.query(`ALTER TABLE \`new_title_request\` DROP FOREIGN KEY \`FK_33b528b4fe87f4167cf39fd123f\``);
        await queryRunner.query(`ALTER TABLE \`new_title_request\` DROP FOREIGN KEY \`FK_c43ae9667d3d70ce8dcef25c814\``);
        await queryRunner.query(`ALTER TABLE \`new_title_request\` DROP FOREIGN KEY \`FK_e8b0487f6e2adba3f7dd38daa16\``);
        await queryRunner.query(`ALTER TABLE \`exhibition_stock\` DROP FOREIGN KEY \`FK_4707c538e0dfbb2916f2c6e57f7\``);
        await queryRunner.query(`ALTER TABLE \`exhibition_stock\` DROP FOREIGN KEY \`FK_88f7647cc25073a57dbc090b9a6\``);
        await queryRunner.query(`ALTER TABLE \`exhibition\` DROP FOREIGN KEY \`FK_502413e750aee25c438c972e2de\``);
        await queryRunner.query(`ALTER TABLE \`exhibition\` DROP FOREIGN KEY \`FK_083d1d8f037bc8591e2f8c14d76\``);
        await queryRunner.query(`ALTER TABLE \`exhibition\` DROP FOREIGN KEY \`FK_0d5dcefa3cff367e6d0ade75cd8\``);
        await queryRunner.query(`ALTER TABLE \`cash_reconciliation\` DROP FOREIGN KEY \`FK_26d6dd44f75ec0a907829b03c12\``);
        await queryRunner.query(`ALTER TABLE \`cash_reconciliation\` DROP FOREIGN KEY \`FK_09cd6f2e176e72e3e96c03f41c5\``);
        await queryRunner.query(`ALTER TABLE \`expense_revision\` DROP FOREIGN KEY \`FK_586a7ef066aa9c3dd2aa65c6901\``);
        await queryRunner.query(`ALTER TABLE \`expense_revision\` DROP FOREIGN KEY \`FK_6098607116ed775b4791cc99b09\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_c9b6a471b795457f5307c477e50\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_6ae83e254854a25f788cf9f3495\``);
        await queryRunner.query(`ALTER TABLE \`branch_inventory\` DROP FOREIGN KEY \`FK_17b568948c94b4ac9314fee3bdd\``);
        await queryRunner.query(`ALTER TABLE \`branch_inventory\` DROP FOREIGN KEY \`FK_6cd826d26d62acf07e7ae226f75\``);
        await queryRunner.query(`ALTER TABLE \`central_stock\` DROP FOREIGN KEY \`FK_2ad058e8f4d1c74cc23d395872f\``);
        await queryRunner.query(`ALTER TABLE \`stock_movement\` DROP FOREIGN KEY \`FK_7484d49153e7188cc2f147f1f90\``);
        await queryRunner.query(`ALTER TABLE \`stock_movement\` DROP FOREIGN KEY \`FK_3695701a949574c5d636d13e218\``);
        await queryRunner.query(`ALTER TABLE \`stock_movement\` DROP FOREIGN KEY \`FK_41586e8268043b2847ec4c9f718\``);
        await queryRunner.query(`ALTER TABLE \`purchase_order_item\` DROP FOREIGN KEY \`FK_32398344c68461ebb37c86935bc\``);
        await queryRunner.query(`ALTER TABLE \`purchase_order_item\` DROP FOREIGN KEY \`FK_1c77f592d2af177be137dac042a\``);
        await queryRunner.query(`ALTER TABLE \`purchase_order\` DROP FOREIGN KEY \`FK_d430e0c1b1e96453b7403795268\``);
        await queryRunner.query(`ALTER TABLE \`purchase_order\` DROP FOREIGN KEY \`FK_3dacab5c4a43cecc0e48f5edb12\``);
        await queryRunner.query(`ALTER TABLE \`restock_request_item\` DROP FOREIGN KEY \`FK_7d2f087c1802f52757cd0d2a52f\``);
        await queryRunner.query(`ALTER TABLE \`restock_request_item\` DROP FOREIGN KEY \`FK_f57c579468c74127aa1500781d8\``);
        await queryRunner.query(`ALTER TABLE \`book\` DROP FOREIGN KEY \`FK_0bfe418ce140d4720d0eede7c3e\``);
        await queryRunner.query(`ALTER TABLE \`book\` DROP FOREIGN KEY \`FK_baaa4c0d27070b4125aa5a81e25\``);
        await queryRunner.query(`ALTER TABLE \`book\` DROP FOREIGN KEY \`FK_24b753b0490a992a6941451f405\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`FK_1117b4fcb3cd4abb4383e1c2743\``);
        await queryRunner.query(`ALTER TABLE \`restock_request\` DROP FOREIGN KEY \`FK_46de05bb7eb9d1d581b6cd8157b\``);
        await queryRunner.query(`ALTER TABLE \`restock_request\` DROP FOREIGN KEY \`FK_6a60b5f26ee8d962e1cda114e59\``);
        await queryRunner.query(`ALTER TABLE \`restock_request\` DROP FOREIGN KEY \`FK_2f71a73309b78681fe8f9af1309\``);
        await queryRunner.query(`ALTER TABLE \`system_setting\` DROP FOREIGN KEY \`FK_811f9e6d65126e0164f87b29a55\``);
        await queryRunner.query(`ALTER TABLE \`refresh_token\` DROP FOREIGN KEY \`FK_6bbe63d2fe75e7f0ba1710351d4\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_token\` DROP FOREIGN KEY \`FK_7eabb22ed38459ffc24dc8b415d\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_b489bba7c2e3d5afcd98a445ff8\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_09210cab0384d041d5f3b337e8e\``);
        await queryRunner.query(`DROP INDEX \`IDX_43fef0ec7f613c19c612fffe62\` ON \`audit_log\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ad7930a7c2af80585c8c1b770\` ON \`audit_log\``);
        await queryRunner.query(`DROP TABLE \`audit_log\``);
        await queryRunner.query(`DROP TABLE \`bill_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_e897f48daabe3b9132f9343232\` ON \`bill\``);
        await queryRunner.query(`DROP INDEX \`IDX_3948e00da8f516a2315cd9e102\` ON \`bill\``);
        await queryRunner.query(`DROP INDEX \`IDX_10443f7ef374882cc97406cb32\` ON \`bill\``);
        await queryRunner.query(`DROP TABLE \`bill\``);
        await queryRunner.query(`DROP TABLE \`book_enquiry\``);
        await queryRunner.query(`DROP TABLE \`new_title_request\``);
        await queryRunner.query(`DROP INDEX \`IDX_444c894652459cf6f9f4fd01b4\` ON \`exhibition_stock\``);
        await queryRunner.query(`DROP TABLE \`exhibition_stock\``);
        await queryRunner.query(`DROP TABLE \`exhibition\``);
        await queryRunner.query(`DROP INDEX \`IDX_476f8f82c63cd5222862f07ff0\` ON \`cash_reconciliation\``);
        await queryRunner.query(`DROP TABLE \`cash_reconciliation\``);
        await queryRunner.query(`DROP TABLE \`expense_revision\``);
        await queryRunner.query(`DROP TABLE \`expense\``);
        await queryRunner.query(`DROP INDEX \`IDX_4c379d2a60ddcd889211ecda17\` ON \`branch_inventory\``);
        await queryRunner.query(`DROP TABLE \`branch_inventory\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ad058e8f4d1c74cc23d395872\` ON \`central_stock\``);
        await queryRunner.query(`DROP TABLE \`central_stock\``);
        await queryRunner.query(`DROP INDEX \`IDX_b69efe8c6a15376cb182f44e57\` ON \`stock_movement\``);
        await queryRunner.query(`DROP INDEX \`IDX_8f9d1d7f22359317d47323bc72\` ON \`stock_movement\``);
        await queryRunner.query(`DROP INDEX \`IDX_9693db35471541ee9be35cbc03\` ON \`stock_movement\``);
        await queryRunner.query(`DROP TABLE \`stock_movement\``);
        await queryRunner.query(`DROP TABLE \`purchase_order_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_a932de191f1a55173e4b985c6e\` ON \`purchase_order\``);
        await queryRunner.query(`DROP TABLE \`purchase_order\``);
        await queryRunner.query(`DROP TABLE \`supplier\``);
        await queryRunner.query(`DROP TABLE \`restock_request_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_cd08784c80b056b4b3ad1d8530\` ON \`book\``);
        await queryRunner.query(`DROP INDEX \`IDX_bd183604b9c828c0bdd92cafab\` ON \`book\``);
        await queryRunner.query(`DROP INDEX \`IDX_c10a44a29ef231062f22b1b7ac\` ON \`book\``);
        await queryRunner.query(`DROP TABLE \`book\``);
        await queryRunner.query(`DROP TABLE \`category\``);
        await queryRunner.query(`DROP TABLE \`publisher\``);
        await queryRunner.query(`DROP TABLE \`author\``);
        await queryRunner.query(`DROP TABLE \`restock_request\``);
        await queryRunner.query(`DROP TABLE \`system_setting\``);
        await queryRunner.query(`DROP INDEX \`IDX_6bbe63d2fe75e7f0ba1710351d\` ON \`refresh_token\``);
        await queryRunner.query(`DROP TABLE \`refresh_token\``);
        await queryRunner.query(`DROP INDEX \`IDX_7eabb22ed38459ffc24dc8b415\` ON \`password_reset_token\``);
        await queryRunner.query(`DROP TABLE \`password_reset_token\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_638479fc29fab932b7ab0aea91\` ON \`branch\``);
        await queryRunner.query(`DROP TABLE \`branch\``);
    }

}
